spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: login@gmail.com
    password: password
    port: 587
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp